#facebook :
#  client :
#    clientId : 230297124573501
#    clientSecret: e54113c95c84cc378530a582cd01f475
#    accessTokenUri: https://graph.facebook.com/oauth/access_token
#    userAuthorizationUri: https://www.facebook.com/dialog/oauth?display=popup
#    tokenName: oauth_token
#    authenticationScheme: query
#    clientAuthenticationScheme: form
#    scope: email
#  resource:
#    userInfoUri: https://graph.facebook.com/me?fields=id,name,email,link
#
#google :
#  client :
#    clientId : 288399508480-8mg7urnlbf2f1178q31gqc3qjolo4bne.apps.googleusercontent.com
#    clientSecret: V94ccCrsT4iRev2xJq3T3fDd
#    accessTokenUri: https://accounts.google.com/o/oauth2/token
#    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
#    scope: email, profile
#  resource:
#    userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo
#
#
#naver :
#  client :
#    clientId : kCyaHRrdbLmYJCppfmAc
#    clientSecret : hHdcU_NMOT
#    accessTokenUri : https://nid.naver.com/oauth2.0/token
#    userAuthorizationUri : https://nid.naver.com/oauth2.0/authorize
#    tokenName : oauth_token
#    authenticationScheme : query
#    clientAuthenticationScheme: form
#  resource:
#    userInfoUri : https://openapi.naver.com/v1/nid/me

spring:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: -
            client-secret: -
          facebook:
            client-id: -
            client-secret: -

custom:
  oauth2:
    kakao:
      client-id: -